# Generated by Django 4.2.6 on 2023-10-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inicio.producto')),
                ('tipo', models.CharField(choices=[('regular', 'Regular'), ('olimpica', 'Olimpica')], max_length=25)),
                ('peso', models.IntegerField()),
            ],
            bases=('inicio.producto',),
        ),
        migrations.CreateModel(
            name='Mancuerna',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inicio.producto')),
                ('peso', models.IntegerField()),
            ],
            bases=('inicio.producto',),
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inicio.producto')),
                ('nombre', models.CharField(max_length=100)),
                ('peso_limite', models.IntegerField()),
                ('instrucciones_de_uso', models.TextField(max_length=500)),
            ],
            bases=('inicio.producto',),
        ),
    ]
